
server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xupt_helper
    username: root
    password: 980508
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
      default-encoding: UTF-8
      host: smtp.qq.com
      port: 25
      username: 1685813197@qq.com
      password: vbwnnnwvcjwodbjf
      properties:
        mail.smtp.auth: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.help.entity
